name: Run Pytest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify Python Module Discovery
      run: python -c "import utils.datareader;"

    - name: Run Pytest tests
      run: |
        pytest tests --setup-show --html=report/report.html

    - name: Upload Pytest Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: report
